[project]
name = "PROJECT"
requires-python = ">= 3.8"
author = {name = "Alex C Warren", email = "alexcwarren.info@gmail.com"}
description = ""
readme = "README.md"
license = {file = "LICENSE"}

[tool.black]
line-length = 89

[tool.flake8]
max-line-length = 88
ignore = ['E203', 'W503']